### ISSUE TITLE
An attempt was made to access a socket in a way forbidden

### ISSUE THREAD

**Issue by KittensScythe** [Zetaphor/solipnet#1]
I've been trying to get this all set up and I can't for the life of me figure out how to fix this error, I'm trying to use oogabooga text ui's local api url for solipnets .env but it just straight out refuses and throws this error at me without fail.

![image](https://github.com/user-attachments/assets/ec04fa40-8601-402b-b53a-64a624e1ac5a)

did I miss something in the .env or am I not supposed to touch the url?

![image](https://github.com/user-attachments/assets/908232be-ccb5-4590-a4bc-ccdf5e86b6c1)

I know it has to do with using the same port but I don't really know another way to link it to text ui's api?

**Comment by KittensScythe** [comment]
I managed to fix it by forcing webui's api port to change but sadly now stuck on these issues..

![image](https://github.com/user-attachments/assets/d591aa33-6e06-48a4-826e-106816852cd7)

**Comment by Zetaphor** [comment]
I've never used Ooga's API before but it looks like something is malformed in the response format from ooga, it appears to not be following the OpenAI API spec.

There shouldn't be any problem changing that base URL entirely or just its port. It needs to be pointing to an OpenAI compatible API

Do you have any logs from Ooga showing its side of this request?

**Comment by KittensScythe** [comment]
> I've never used Ooga's API before but it looks like something is malformed in the response format from ooga, it appears to not be following the OpenAI API spec.
> 
> There shouldn't be any problem changing that base URL entirely or just its port. It needs to be pointing to an OpenAI compatible API
> 
> Do you have any logs from Ooga showing its side of this request?

Can't seem to even find any logs regarding startup, only strangely find chatlogs from past use with models. 
Do you recommend another webui to run with it? might be better to straight out try another that's known to work rather then making shots in the dark I guess

**Comment by Zetaphor** [comment]
I was testing this against the API server in LM Studio, which provides an OpenAI compatible API server. In theory anything else that also follow that spec should work
